### ISSUE TITLE
tagging: document 'hidden' tags

### ISSUE THREAD

**Issue by dericed** [Matroska-Org/matroska-specification#19] opened 2016-05-26 03:42 UTC
I'm not sure what these are official called but I see the use of many tags that are prefixed with an underscore, such as _DURATION. From what I can tell these are internal and intended to be hidden from the user in some cases. If this is so, the pattern of hidden tags (vs official and unofficial tags) should be documented.

**Comment by robUx4** [comment] 2017-07-20 16:30
Duplicate of #49 that has more info.

**Closed by robUx4** 2017-07-20 16:30 UTC
Labels: clarifications, tags
